/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Matt
 */
public class LoginPanel extends javax.swing.JPanel
{

    /**
     * Creates new form LoginPanel
     */
    public LoginPanel()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        txtFieldUsername = new java.awt.TextField();
        lblPassword = new javax.swing.JLabel();
        txtFieldPassword = new java.awt.TextField();
        btnLogin = new javax.swing.JButton();
        btnCreateNewAccount = new javax.swing.JButton();
        textArea1 = new java.awt.TextArea();

        setMinimumSize(new java.awt.Dimension(700, 400));
        setPreferredSize(new java.awt.Dimension(700, 400));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Login"));
        jPanel1.setMinimumSize(new java.awt.Dimension(700, 400));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 400));

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 5));

        lblUsername.setText("Username");
        jPanel2.add(lblUsername);

        txtFieldUsername.setMinimumSize(new java.awt.Dimension(100, 20));
        txtFieldUsername.setName(""); // NOI18N
        txtFieldUsername.setPreferredSize(new java.awt.Dimension(100, 20));
        txtFieldUsername.setText("Username");
        txtFieldUsername.setSelectionEnd(-1);
        txtFieldUsername.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtFieldUsernameActionPerformed(evt);
            }
        });
        jPanel2.add(txtFieldUsername);

        lblPassword.setText("Password");
        lblPassword.setMaximumSize(new java.awt.Dimension(55, 20));
        lblPassword.setMinimumSize(new java.awt.Dimension(55, 20));
        lblPassword.setPreferredSize(new java.awt.Dimension(55, 20));
        jPanel2.add(lblPassword);

        txtFieldPassword.setMinimumSize(new java.awt.Dimension(100, 20));
        txtFieldPassword.setPreferredSize(new java.awt.Dimension(100, 20));
        txtFieldPassword.setText("Password");
        txtFieldPassword.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtFieldPasswordActionPerformed(evt);
            }
        });
        jPanel2.add(txtFieldPassword);

        btnLogin.setText("Login");
        jPanel2.add(btnLogin);

        btnCreateNewAccount.setText("Create New Account");
        jPanel2.add(btnCreateNewAccount);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textArea1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFieldPasswordActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtFieldPasswordActionPerformed
    {//GEN-HEADEREND:event_txtFieldPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldPasswordActionPerformed

    private void txtFieldUsernameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtFieldUsernameActionPerformed
    {//GEN-HEADEREND:event_txtFieldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldUsernameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateNewAccount;
    private javax.swing.JButton btnLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private java.awt.TextArea textArea1;
    private java.awt.TextField txtFieldPassword;
    private java.awt.TextField txtFieldUsername;
    // End of variables declaration//GEN-END:variables
}
